### ISSUE TITLE
Feat: Add support for custom scarb target build profile

### ISSUE THREAD

**Issue by julio4** [software-mansion/cairo-coverage#148]
`cairo-coverage` use default `dev` build profile.

This can be inconvenient in specific situation where we want to use a different profile.

One example situation is using coverage only in CI/CD, to reduce the compilation overhead added with `unstable-add-statements-code-locations-debug-info` and `unstable-add-statements-functions-debug-info` one could define a custom `ci` profile:
```toml
// Scarb.toml
// ...
[profile.ci.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
```

And verify tests in the CI with `SCARB_PROFILE=ci snforge test --save-trace-data`, then use cairo-coverage with suggested:
```
SCARB_PROFILE=ci cairo-coverage <TRACE_FILES>
// or
cairo-coverage <TRACE_FILES> --profile ci
```

This is currently not possible as it fails with:
```
Error: Inference of project path failed.
Please provide the project path explicitly using the --project-path flag.

Caused by:
    Source sierra path should be in the format: <project_root>/target/dev/<file>.contract_class.json, got: <project_root>/target/ci/<file>.contract_class.json
```

The current way to make it works is to pass the project-path:  
`SCARB_PROFILE=ci cairo-coverage <TRACE_FILES> --project-path <PATH>`
