### ISSUE TITLE
Validate Scarb.toml Configuration in Forge for Trace Data File Generation and Validate Scarb version

### ISSUE THREAD

**Issue by ksew1** [software-mansion/cairo-coverage#48]
Currently, generating trace files requires using Scarb version `2.8.0` or higher and including specific configurations in the `Scarb.toml` file. This requirement is documented, but it would be beneficial to add validation of these configurations in Forge with meaningful error messages to assist users more effectively.

---
1. **Scarb Version Check:**
   - Ensure that the Scarb version is `2.8.0` or higher.

2. **`Scarb.toml` Configuration Validation:**
   - Validate that the `Scarb.toml` file includes the following configurations under the `[cairo]` section:
     ```toml
     [cairo]
     unstable-add-statements-code-locations-debug-info = true
     unstable-add-statements-functions-debug-info = true
     inlining-strategy = "avoid"
     ```
